-- Global settings

BINDING_HEADER_SHEEPWATCH = "SheepWatch Bindings";
BINDING_NAME_SHEEPWATCHSHEEP = "Polymorph your target";
BINDING_NAME_SHEEPWATCHRETARGET = "Retarget your sheep";

function SheepWatch_Globals()

SHEEPWATCH = {}
SHEEPWATCH.LASTUPDATE = 0
SHEEPWATCH.UPDATEINT = 0.1
SHEEPWATCH.ACTIVE = false
SHEEPWATCH.STATUS = 1 		-- 0: Disabled 1: Enabled 2: Visible/Active 3: Unlocked
SHEEPWATCH.TIMER_START = 0
SHEEPWATCH.TIMER_END = -15
SHEEPWATCH.MOBGUID = 0
SHEEPWATCH.SHEEPTYPE = SHEEPWATCH_SPELL
SHEEPWATCH.LENGTH = 20 		-- Default to Polymorph Rank 1 (20 seconds)
SHEEPWATCH.RANK = ""
SHEEPWATCH.COUNTER = false
SHEEPWATCH.DECIMALS = true 							
SHEEPWATCH.SOUND = true
SHEEPWATCH.DIRECTION = 1									
SHEEPWATCH.SCALE = 1
SHEEPWATCH.DEBUFF = "Spell_Nature_Polymorph"
SHEEPWATCH.DIRECTION = 1
SHEEPWATCH["barcolor"] =	{
					{ r = "1.0", g = "1.0", b = "0.0"}
				}
SHEEPWATCH.ANNOUNCESCAST = 1    -- SAY
SHEEPWATCH.ANNOUNCEST30 = 1
SHEEPWATCH.ANNOUNCEST20 = 1
SHEEPWATCH.ANNOUNCEST15 = 1
SHEEPWATCH.ANNOUNCEST10 = 1
SHEEPWATCH.ANNOUNCEST5 = 1
SHEEPWATCH.ANNOUNCEST4 = 1
SHEEPWATCH.ANNOUNCEST3 = 1
SHEEPWATCH.ANNOUNCEST2 = 1
SHEEPWATCH.ANNOUNCEST1 = 1
SHEEPWATCH.ANNOUNCESEND = 1
SHEEPWATCH.ANNOUNCESWHO = 1

SHEEPWATCH.ANNOUNCEPCAST = 1    -- PARTY
SHEEPWATCH.ANNOUNCEPT30 = 1
SHEEPWATCH.ANNOUNCEPT20 = 1
SHEEPWATCH.ANNOUNCEPT15 = 1
SHEEPWATCH.ANNOUNCEPT10 = 1
SHEEPWATCH.ANNOUNCEPT5 = 1
SHEEPWATCH.ANNOUNCEPT4 = 1
SHEEPWATCH.ANNOUNCEPT3 = 1
SHEEPWATCH.ANNOUNCEPT2 = 1
SHEEPWATCH.ANNOUNCEPT1 = 1
SHEEPWATCH.ANNOUNCEPEND = 1
SHEEPWATCH.ANNOUNCEPWHO = 1

SHEEPWATCH.ANNOUNCERCAST = 1	-- RAID
SHEEPWATCH.ANNOUNCERT30 = 1
SHEEPWATCH.ANNOUNCERT20 = 1
SHEEPWATCH.ANNOUNCERT15 = 1
SHEEPWATCH.ANNOUNCERT10 = 1
SHEEPWATCH.ANNOUNCERT5 = 1
SHEEPWATCH.ANNOUNCERT4 = 1
SHEEPWATCH.ANNOUNCERT3 = 1
SHEEPWATCH.ANNOUNCERT2 = 1
SHEEPWATCH.ANNOUNCERT1 = 1
SHEEPWATCH.ANNOUNCEREND = 1
SHEEPWATCH.ANNOUNCERWHO = 1

SHEEPWATCH.ALPHA = 1
SHEEPWATCH.LOCKED = true

				-- Ability to clear users profile when neccessary
SHEEPWATCH.CLEAR = true

SHEEPWATCH_PROFILE = ""
SHEEPWATCH_VARIABLES_LOADED = false

SheepWatch_Settings = {}

end